## Set up primary generaotr
/control/execute primaryGeneratorSetup.mac
#/control/execute ../macro/primaryGeneratorSetup_H_Matthia2013_W_0.mac

## Set up visulalization ennrionment
/control/execute visSetup.mac

## Set up verbosity
/control/execute verboseSetup.mac

## Set up multithread
#/control/cout/ignoreThreadsExcept 0

## Invoke the application
/run/printProgress 10000000
# /run/beamOn 1
#/run/beamOn 1000000000

