/vis/verbose 1

## Specify the viewer
/vis/open VRML2FILE

## Draw geometry
/vis/drawVolume world #volumes

## Draw coordinate axes
/vis/scene/add/axes 0 0 0 5 m #Axes (x=red, y=green, z=blue)

## Draw trajectory
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate #superimpose all of the events

#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)

# Particle filter
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add neutron
#/vis/filtering/trajectories/particleFilter-0/add gamma

# To invert the above
#/vis/filtering/trajectories/particleFilter-0/invert true

# Select color by particle ID:
/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 1

# To select or override default colours (note: e+ is blue by default):
#/vis/modeling/trajectories/list
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow

## Draw hits
#/vis/scene/add/hits

## Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style wireframe #volume style (surface/wireframe)
/vis/viewer/set/auxiliaryEdge true #show edges of curved surfaces
/vis/viewer/set/lineSegmentsPerCircle 100 #make circles smoothed
/vis/viewer/set/rotationStyle freeRotation

## Specify view angle
/vis/viewer/set/upVector 0 0 1
#/vis/viewer/set/viewpointThetaPhi 120 150 deg
/vis/viewer/set/viewpointVector 1 0.2 0.2
#/vis/viewer/set/viewpointVector 0 0 1

## Specify zoom value
#/vis/viewer/zoom 1.4

## Specify cataway
#/vis/viewer/addCutawayPlane 0 0 0 m 0 0 -1

